export default function HomePage() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-2xl font-bold">{{ProjectName}}</h1>
      <p className="text-gray-500 mt-2">Generated by StackAlchemist.</p>

      {{!-- LLM_INJECTION_START: HomePageContent --}}
      {{!--
        The LLM will generate entity listing sections here.
        One section per entity with a link to /api/v1/{entityLower}s
      --}}
      {{!-- LLM_INJECTION_END: HomePageContent --}}
    </main>
  );
}
