using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using StackAlchemist.Engine.Services;

namespace StackAlchemist.Engine.Tests.Services;

/// <summary>
/// Proves the C# BYOK decryption is byte-for-byte compatible with the Next.js
/// <c>encryptApiKeyOverride</c> scheme (scrypt N=16384/r=8/p=1 + AES-256-GCM). The
/// <see cref="GoldenSecret"/>/<see cref="GoldenPlaintext"/>/<see cref="GoldenCiphertext"/> triple
/// was produced by running the REAL Node crypto (see PR notes) and is hard-coded here so a
/// regression in the scrypt params, salt, or envelope parsing fails this test.
/// </summary>
public class ByokKeyProtectorTests
{
    // Generated by running the Node encryptApiKeyOverride with GoldenSecret + GoldenPlaintext.
    internal const string GoldenSecret = "golden-vector-byok-secret-000000000000000000";
    internal const string GoldenPlaintext = "sk-ant-api03-GOLDEN-vector-plaintext-key-1234567890";
    internal const string GoldenCiphertext =
        "v1:SEeiqD6hCr6/RsfD:xAvF0jLBBgPVwCo2VC7ZUA==:iW0hz1XyJlEGU3zoigbjVZI12NdttLCf4Av8+AoXgGIxW6lvt3E3J/tWplWnM37ymaf1";

    private static ByokKeyProtector Build(string? byokKey = GoldenSecret, string? engineKey = null) =>
        new(
            new ConfigurationBuilder()
                .AddInMemoryCollection(new Dictionary<string, string?>
                {
                    ["Byok:EncryptionKey"] = byokKey,
                    ["Engine:ServiceKey"] = engineKey,
                })
                .Build(),
            NullLogger<ByokKeyProtector>.Instance);

    [Fact]
    public void TryDecrypt_GoldenVector_RecoversPlaintext()
    {
        var protector = Build();

        protector.TryDecrypt(GoldenCiphertext).Should().Be(GoldenPlaintext);
    }

    [Fact]
    public void TryDecrypt_UsesEngineServiceKeyFallback_WhenByokKeyUnset()
    {
        // Backward-compat: keys saved before the distinct BYOK_ENCRYPTION_KEY requirement were
        // encrypted with ENGINE_SERVICE_KEY and must still decrypt.
        var protector = Build(byokKey: null, engineKey: GoldenSecret);

        protector.TryDecrypt(GoldenCiphertext).Should().Be(GoldenPlaintext);
    }

    [Fact]
    public void TryDecrypt_WrongSecret_ReturnsNull()
    {
        var protector = Build(byokKey: "a-completely-different-32-char-secret!!!!");

        protector.TryDecrypt(GoldenCiphertext).Should().BeNull();
    }

    [Theory]
    [InlineData("not-an-envelope")]
    [InlineData("v1:onlytwo:parts")]
    [InlineData("v2:SEeiqD6hCr6/RsfD:xAvF0jLBBgPVwCo2VC7ZUA==:iW0hz1XyJlEG")] // wrong version tag
    [InlineData("v1:!!!notbase64!!!:xAvF0jLBBgPVwCo2VC7ZUA==:iW0hz1Xy")] // bad base64
    public void TryDecrypt_MalformedCiphertext_ReturnsNull(string ciphertext)
    {
        var protector = Build();

        protector.TryDecrypt(ciphertext).Should().BeNull();
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    public void TryDecrypt_MissingCiphertext_ReturnsNull(string? ciphertext)
    {
        var protector = Build();

        protector.TryDecrypt(ciphertext).Should().BeNull();
    }

    [Fact]
    public void TryDecrypt_UnconfiguredSecret_ReturnsNull()
    {
        var protector = Build(byokKey: null, engineKey: null);

        protector.TryDecrypt(GoldenCiphertext).Should().BeNull();
    }

    [Fact]
    public void TryDecrypt_ShortSecret_ReturnsNull()
    {
        // A secret under 32 chars can't have produced a real stored key — refuse it.
        var protector = Build(byokKey: "too-short");

        protector.TryDecrypt(GoldenCiphertext).Should().BeNull();
    }
}
