import Link from "next/link";

export default function HomePage() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-2xl font-bold">{{ProjectName}}</h1>
      <p className="text-gray-500 mt-2">Generated by StackAlchemist.</p>

      <nav className="mt-8 space-y-2">
        {{#each Entities}}
        <Link href="/{{NameLower}}s" className="block text-blue-600 hover:underline">
          {{Name}}s
        </Link>
        {{/each}}
      </nav>
    </main>
  );
}
