import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "{{ProjectName}}",
  description: "A live demo generated by StackAlchemist",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
