-- {{ProjectName}} — Initial Schema
-- Generated by StackAlchemist v1

[[LLM_INJECTION_START: SqlSchema]]
{{!--
  The LLM will generate CREATE TABLE statements per entity here.
  Expected format:

  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

  CREATE TABLE {table_name} (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      {field_name} {sql_type} NOT NULL,
      ...
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  -- Foreign key constraints follow table definitions
  ALTER TABLE {child_table} ADD CONSTRAINT fk_{child}_{parent}
      FOREIGN KEY ({fk_column}) REFERENCES {parent_table}(id) ON DELETE CASCADE;

  -- RLS
  ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY;
--}}
[[LLM_INJECTION_END: SqlSchema]]
