export default function App() {
  return (
    <main className="min-h-screen bg-gray-50 p-8">
      <h1 className="text-3xl font-bold text-gray-900">{{ProjectName}}</h1>
      <p className="mt-2 text-gray-600">Generated by StackAlchemist.</p>
      {{!-- LLM_INJECTION_START: HomePageContent --}}
      {/* LLM generates entity listing sections here */}
      {{!-- LLM_INJECTION_END: HomePageContent --}}
    </main>
  );
}
