services:
  sa-web:
    container_name: sa-web
    build:
      context: ..
      target: web
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    restart: always

  sa-engine:
    container_name: sa-engine
    build:
      context: ..
      target: engine
    ports:
      - "5000:80"
    env_file:
      - ../.env
    restart: always

  sa-worker:
    container_name: sa-worker
    build:
      context: ..
      target: worker
    env_file:
      - ../.env
    restart: always
