server {
    listen 3000;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index maintenance.html;
        try_files $uri /maintenance.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header X-Maintenance "1";
    }
}
