apiVersion: v1
kind: Secret
metadata:
  name: {{ include "{{ProjectNameKebab}}.fullname" . }}
  labels:
    {{- include "{{ProjectNameKebab}}.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
