-- {{ProjectName}} — Initial Schema
-- Generated by StackAlchemist v1

{{!-- LLM_INJECTION_START: SqlSchema --}}
-- LLM generates:
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- CREATE TABLE entities (...)
-- ALTER TABLE for foreign keys
{{!-- LLM_INJECTION_END: SqlSchema --}}
