export interface SolutionEntry {
  slug: string;
  vertical: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  relativePath: string;
  entityExamples: readonly string[];
  primaryKeywords: readonly string[];
  updatedAt: string;
}

export const SOLUTION_ENTRIES = [
  {
    slug: "ai-ecommerce-platform",
    vertical: "AI E-commerce Platform",
    h1: "Generate a full AI E-commerce Platform from a prompt",
    metaTitle: "AI E-commerce Platform Generator — Compile-Guaranteed SaaS",
    metaDescription:
      "Generate a full .NET 10 + Next.js 15 AI-powered e-commerce platform with Stripe, auth, and inventory in 12 minutes. Verified build, owned code, one-time price.",
    relativePath: "ai-ecommerce-platform.md",
    entityExamples: [
      "Product",
      "Variant",
      "Inventory",
      "Cart",
      "Order",
      "Customer",
      "Review",
      "PromoCode",
    ],
    primaryKeywords: [
      "ai ecommerce platform",
      "ai ecommerce builder",
      "ai shopify alternative",
      "generate ecommerce saas",
    ],
    updatedAt: "2026-04-16",
  },
  {
    slug: "ai-lms-builder",
    vertical: "AI LMS Builder",
    h1: "Generate a full AI Learning Management System from a prompt",
    metaTitle: "AI LMS Builder — Generate a Full Learning Platform in Minutes",
    metaDescription:
      "Generate a full .NET 10 + Next.js 15 AI-powered LMS with courses, lessons, quizzes, enrollments, and Stripe billing. Verified build, owned code, one-time price.",
    relativePath: "ai-lms-builder.md",
    entityExamples: [
      "Course",
      "Lesson",
      "Module",
      "Quiz",
      "Question",
      "Enrollment",
      "Student",
      "Instructor",
    ],
    primaryKeywords: [
      "ai lms builder",
      "ai learning management system",
      "ai course platform generator",
      "ai teachable alternative",
    ],
    updatedAt: "2026-04-16",
  },
  {
    slug: "fintech-saas-generator",
    vertical: "Fintech SaaS Generator",
    h1: "Generate a full Fintech SaaS from a prompt",
    metaTitle: "Fintech SaaS Generator — Generate a Compliant Finance Platform",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 fintech SaaS with accounts, transactions, KYC hooks, audit trails, and Stripe. Verified build, owned code, one-time price.",
    relativePath: "fintech-saas-generator.md",
    entityExamples: [
      "Account",
      "Transaction",
      "Ledger",
      "KycProfile",
      "AuditEvent",
      "Institution",
      "PaymentMethod",
    ],
    primaryKeywords: [
      "fintech saas generator",
      "generate fintech platform",
      "ai fintech builder",
      "fintech codegen",
    ],
    updatedAt: "2026-04-16",
  },
  {
    slug: "ai-crm-builder",
    vertical: "AI CRM Builder",
    h1: "Generate a full AI CRM from a prompt",
    metaTitle: "AI CRM Builder — Generate a Custom CRM SaaS in Minutes",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 CRM with contacts, deals, pipelines, tasks, and email integration. Verified build, owned code, one-time price — no Salesforce tax.",
    relativePath: "ai-crm-builder.md",
    entityExamples: [
      "Contact",
      "Account",
      "Deal",
      "Pipeline",
      "Stage",
      "Activity",
      "Task",
      "Note",
    ],
    primaryKeywords: [
      "ai crm builder",
      "generate crm saas",
      "custom crm generator",
      "ai salesforce alternative",
    ],
    updatedAt: "2026-05-09",
  },
  {
    slug: "ai-marketplace-platform",
    vertical: "AI Marketplace Platform",
    h1: "Generate a full AI Marketplace Platform from a prompt",
    metaTitle: "AI Marketplace Generator — Generate a Two-Sided Marketplace SaaS",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 two-sided marketplace with listings, vendors, buyers, payouts, and Stripe Connect. Verified build, owned code, one-time price.",
    relativePath: "ai-marketplace-platform.md",
    entityExamples: [
      "Listing",
      "Vendor",
      "Buyer",
      "Order",
      "Payout",
      "Review",
      "Category",
      "Dispute",
    ],
    primaryKeywords: [
      "ai marketplace generator",
      "generate marketplace saas",
      "two sided marketplace builder",
      "ai marketplace platform",
    ],
    updatedAt: "2026-05-09",
  },
  {
    slug: "ai-jobboard-builder",
    vertical: "AI Job Board Builder",
    h1: "Generate a full AI Job Board from a prompt",
    metaTitle: "AI Job Board Builder — Generate a Niche Job Board SaaS",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 niche job board with listings, employer accounts, applicants, billing, and an admin panel. Verified build, owned code, one-time price.",
    relativePath: "ai-jobboard-builder.md",
    entityExamples: [
      "JobListing",
      "Employer",
      "Applicant",
      "Application",
      "Subscription",
      "Category",
      "Location",
      "FeaturedSlot",
    ],
    primaryKeywords: [
      "ai job board builder",
      "niche job board generator",
      "generate job board saas",
      "ai jobboard codegen",
    ],
    updatedAt: "2026-05-09",
  },
  {
    slug: "ai-analytics-saas",
    vertical: "AI Analytics SaaS",
    h1: "Generate a full AI Analytics SaaS from a prompt",
    metaTitle: "AI Analytics SaaS Generator — Owned Product Analytics",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 product-analytics SaaS with event ingestion, dashboards, custom reports, alerting, and usage billing. Owned code, one-time price.",
    relativePath: "ai-analytics-saas.md",
    entityExamples: [
      "Event",
      "EventSchema",
      "Workspace",
      "Dashboard",
      "Widget",
      "SavedQuery",
      "Alert",
      "UsageRecord",
    ],
    primaryKeywords: [
      "ai analytics saas generator",
      "owned product analytics",
      "amplitude alternative codegen",
      "build analytics saas",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-healthcare-patient-portal",
    vertical: "AI Healthcare Patient Portal",
    h1: "Generate a full AI Healthcare Patient Portal from a prompt",
    metaTitle: "AI Healthcare Patient Portal Generator — Owned, Audit-Logged",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 patient portal with records, scheduling, secure messaging, prescriptions, and audit logging. HIPAA-consistent foundation, owned outright.",
    relativePath: "ai-healthcare-patient-portal.md",
    entityExamples: [
      "Patient",
      "Provider",
      "Appointment",
      "Availability",
      "MessageThread",
      "Prescription",
      "Document",
      "AuditEvent",
    ],
    primaryKeywords: [
      "ai patient portal generator",
      "healthcare saas codegen",
      "telehealth portal builder",
      "epic alternative for clinics",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-project-management-saas",
    vertical: "AI Project Management SaaS",
    h1: "Generate a full AI Project Management SaaS from a prompt",
    metaTitle: "AI Project Management SaaS Generator — Owned Jira Alternative",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 project management SaaS with kanban, sprints, time tracking, dependencies, and reports. No per-seat tax. Owned code, one-time price.",
    relativePath: "ai-project-management-saas.md",
    entityExamples: [
      "Workspace",
      "Project",
      "Task",
      "Sprint",
      "TimeEntry",
      "Comment",
      "Dependency",
      "Membership",
    ],
    primaryKeywords: [
      "ai project management saas",
      "generate jira alternative",
      "custom pm tool codegen",
      "owned project management software",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-real-estate-platform",
    vertical: "AI Real Estate Platform",
    h1: "Generate a full AI Real Estate Platform from a prompt",
    metaTitle: "AI Real Estate Platform Generator — Owned Brokerage SaaS",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 real estate platform with listings, agents, leads, MLS sync, geo search, and showing scheduling. Owned code, one-time price.",
    relativePath: "ai-real-estate-platform.md",
    entityExamples: [
      "Listing",
      "ListingMedia",
      "Agent",
      "Lead",
      "Showing",
      "SearchAlert",
      "MLSImport",
      "Brokerage",
    ],
    primaryKeywords: [
      "ai real estate platform generator",
      "brokerage saas codegen",
      "owned mls site builder",
      "proptech codegen",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-food-delivery-platform",
    vertical: "AI Food Delivery Platform",
    h1: "Generate a full AI Food Delivery Platform from a prompt",
    metaTitle: "AI Food Delivery Platform Generator — Zero Commission Stack",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 food delivery platform with menus, orders, driver dispatch, delivery zones, and Stripe payouts. Cut DoorDash commissions. Owned code, one-time price.",
    relativePath: "ai-food-delivery-platform.md",
    entityExamples: [
      "Restaurant",
      "MenuItem",
      "Modifier",
      "Order",
      "Customer",
      "Driver",
      "DeliveryZone",
      "Payout",
    ],
    primaryKeywords: [
      "ai food delivery platform generator",
      "doordash alternative codegen",
      "restaurant ordering saas",
      "ghost kitchen marketplace builder",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-event-ticketing-platform",
    vertical: "AI Event Ticketing Platform",
    h1: "Generate a full AI Event Ticketing Platform from a prompt",
    metaTitle: "AI Event Ticketing Platform Generator — Own Your Attendees",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 event ticketing platform with seat maps, QR tickets, check-in, and Stripe payouts. Beat Eventbrite fees. Owned code, one-time price.",
    relativePath: "ai-event-ticketing-platform.md",
    entityExamples: [
      "Event",
      "TicketType",
      "Ticket",
      "Order",
      "Attendee",
      "Scanner",
      "SeatMap",
      "Organizer",
    ],
    primaryKeywords: [
      "ai event ticketing platform generator",
      "eventbrite alternative codegen",
      "ticketing saas builder",
      "venue ticketing software",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-inventory-management-saas",
    vertical: "AI Inventory Management SaaS",
    h1: "Generate a full AI Inventory Management SaaS from a prompt",
    metaTitle: "AI Inventory Management SaaS Generator — Unlimited Seats",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 inventory SaaS with SKUs, multi-warehouse stock, purchase orders, suppliers, and reorder alerts. No per-seat tax. Owned code, one-time price.",
    relativePath: "ai-inventory-management-saas.md",
    entityExamples: [
      "SKU",
      "StockLevel",
      "Warehouse",
      "Supplier",
      "PurchaseOrder",
      "Transfer",
      "ReorderRule",
      "CostLayer",
    ],
    primaryKeywords: [
      "ai inventory management saas generator",
      "netsuite alternative codegen",
      "multi warehouse inventory builder",
      "owned wms software",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-hr-onboarding-platform",
    vertical: "AI HR Onboarding Platform",
    h1: "Generate a full AI HR Onboarding Platform from a prompt",
    metaTitle: "AI HR Onboarding Platform Generator — No Per-Seat Tax",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 HR onboarding platform with checklists, document signing, org charts, and equipment provisioning. Beat BambooHR seat pricing. Owned code, one-time price.",
    relativePath: "ai-hr-onboarding-platform.md",
    entityExamples: [
      "Employee",
      "OnboardingFlow",
      "ChecklistItem",
      "Document",
      "Signature",
      "EquipmentRequest",
      "OrgUnit",
      "Manager",
    ],
    primaryKeywords: [
      "ai hr onboarding platform generator",
      "bamboohr alternative codegen",
      "custom onboarding saas",
      "owned hr software builder",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-customer-support-platform",
    vertical: "AI Customer Support Platform",
    h1: "Generate a full AI Customer Support Platform from a prompt",
    metaTitle: "AI Customer Support Platform Generator — Own Your Support Data",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 customer support SaaS with tickets, multi-channel intake, SLA tracking, knowledge base, and CSAT. Beat Zendesk per-agent pricing. Owned code, one-time price.",
    relativePath: "ai-customer-support-platform.md",
    entityExamples: [
      "Ticket",
      "Customer",
      "Agent",
      "Channel",
      "Macro",
      "SLA",
      "KnowledgeArticle",
      "CSATResponse",
    ],
    primaryKeywords: [
      "ai customer support platform generator",
      "zendesk alternative codegen",
      "helpdesk saas builder",
      "owned support software",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-fitness-subscription-platform",
    vertical: "AI Fitness Subscription Platform",
    h1: "Generate a full AI Fitness Subscription Platform from a prompt",
    metaTitle: "AI Fitness Subscription Platform Generator — Keep Member Revenue",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 fitness subscription SaaS with members, classes, check-ins, waitlists, and Stripe recurring billing. Beat Mindbody fees. Owned code, one-time price.",
    relativePath: "ai-fitness-subscription-platform.md",
    entityExamples: [
      "Member",
      "Plan",
      "Class",
      "Instructor",
      "Booking",
      "Checkin",
      "Waitlist",
      "Subscription",
    ],
    primaryKeywords: [
      "ai fitness subscription platform generator",
      "mindbody alternative codegen",
      "boutique studio saas",
      "gym management software builder",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-appointment-booking-saas",
    vertical: "AI Appointment Booking SaaS",
    h1: "Generate a full AI Appointment Booking SaaS from a prompt",
    metaTitle: "AI Appointment Booking SaaS Generator — Branded, No Per-Seat",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 appointment booking SaaS with services, availability, deposits, reminders, and recurring appointments. Beat Calendly seat pricing. Owned code, one-time price.",
    relativePath: "ai-appointment-booking-saas.md",
    entityExamples: [
      "Service",
      "Staff",
      "Availability",
      "Appointment",
      "Customer",
      "Reminder",
      "Deposit",
      "Cancellation",
    ],
    primaryKeywords: [
      "ai appointment booking saas generator",
      "calendly alternative codegen",
      "scheduling software builder",
      "owned booking platform",
    ],
    updatedAt: "2026-05-26",
  },
  {
    slug: "ai-logistics-tracking-saas",
    vertical: "AI Logistics Tracking SaaS",
    h1: "Generate a full AI Logistics Tracking SaaS from a prompt",
    metaTitle: "AI Logistics Tracking SaaS Generator — Own Your Ops Data",
    metaDescription:
      "Generate a .NET 10 + Next.js 15 logistics SaaS with shipments, routes, driver dispatch, POD capture, and billing. Beat Onfleet per-driver pricing. Owned code, one-time price.",
    relativePath: "ai-logistics-tracking-saas.md",
    entityExamples: [
      "Shipment",
      "Route",
      "Driver",
      "Vehicle",
      "ProofOfDelivery",
      "Exception",
      "Customer",
      "BillingRecord",
    ],
    primaryKeywords: [
      "ai logistics tracking saas generator",
      "onfleet alternative codegen",
      "last mile delivery software",
      "owned fleet management builder",
    ],
    updatedAt: "2026-05-26",
  },
] as const satisfies readonly SolutionEntry[];

export function getSolutionBySlug(slug: string): SolutionEntry | undefined {
  return SOLUTION_ENTRIES.find((e) => e.slug === slug);
}

export function getAllSolutionSlugs(): string[] {
  return SOLUTION_ENTRIES.map((e) => e.slug);
}
