import { Link } from "react-router-dom";

export default function App() {
  return (
    <main className="min-h-screen bg-gray-50 p-8">
      <h1 className="text-3xl font-bold text-gray-900">{{ProjectName}}</h1>
      <p className="mt-2 text-gray-600">Generated by StackAlchemist.</p>

      <nav className="mt-8 space-y-2">
        {{#each Entities}}
        <Link to="/{{NameLower}}s" className="block text-blue-600 hover:underline">
          {{Name}}s
        </Link>
        {{/each}}
      </nav>
    </main>
  );
}
